name: Docker GCP deployment

on:
  push:
    branches:
      - 20-deployment-of-louis-backend
  pull_request:

jobs:
  build:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-build-container.yml@main
    with:
      container-name: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}
    secrets: inherit

  deploy:
    needs: build
    uses: ai-cfia/github-workflows/.github/workflows/workflow-deploy-gcp.yml@main
    with:
      container-name: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}
    secrets: inherit